# This is a basic workflow to help you get started with Actions

name: Create Release when a semver-looking Tag is Pushed

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Gets the version number from the pachage.json file
      # - name: Read version from package.json
      #   uses: culshaw/read-package-node-version-actions@v2
      #   id: version
      
      # Build the package
      - run: npm install
      - run: npm run build
      
      # Pack up the library and output the packed tarball file path
      - id: pack
        run: |
          npm pack
          echo "::set-output name=tarball::$(npm pack --dry-run --quiet)"
          
      # TODO: should probably split the publish into a separate "job" here and use
      #  https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs 
      
      # Publish the release
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            "${{ steps.pack.outputs.tarball }}"
