name: Create a tag any time package.json's version changes
on:
  push:
    branches:
      - prod
    paths:
      - package.json
jobs:
  tag-npm-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-tag-on-npm-version@v1.0.1
